### PR TITLE
Foxy: Restore tf frame prefix support for ROS 2 (#159)

### PR DESCRIPTION
**Pull request by clalancette**
quick and dirty frame_prefix support for foxy

Also make it so we don't handle / specially.
Add in tests and documentation as well.

Co-authored-by: Chris Lalancette <clalancette@openrobotics.org>

This is an ABI compatible version of #159 for Foxy.

### CODE REVIEW

**Comment by clalancette** [comment]
@sloretz Friendly ping on this one; this is the last backport of this feature, then we'll have it in Foxy, Galactic, and Rolling.

**Review by sloretz — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14971/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9712/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12651/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15135/)

**Comment by clalancette** [comment]
The warnings on Windows are well-known, and not because of this PR.  I'm going to go ahead and merge this and do a release for Foxy.

**Comment by clalancette** [comment]
Thanks for the review!

**Pull request merged**
