### PR TITLE
Publish fixed joints over tf_static by default

### PR DESCRIPTION
**Pull request by paulbovbel**
As per discussion with @wjwwood and @isucan, we want to make this default for jade

### CODE REVIEW

**Comment by paulbovbel** [comment]
@jacquelinekay, please take a look. Also, can you please cut a release of indigo/jade when convenient?

**Comment by jackieokay** [comment]
I don't know the context behind the discussion, but the idea sounds good to me, and the content clearly agrees with the title of the PR.

**Comment by paulbovbel** [comment]
Discussion was in the prior PR for indigo, thanks

**Comment by wjwwood** [comment]
https://github.com/ros/robot_state_publisher/pull/28 (please link to things you're referring to, we don't all know what which one you're talking about :smile:)

**Pull request merged**
