### PR TITLE
adds orocos_kdl dependency and linking rules (fixes #8)

### LINKED ISSUE #8: robot state publisher failing on buildfarm
http://www.ros.org/debbuild/hydro.html?q=robot_state_publisher

Extract from the build log:

```
Linking CXX executable devel/lib/robot_state_publisher/robot_state_publisher
/usr/bin/cmake -E cmake_link_script CMakeFiles/robot_state_publisher.dir/link.txt --verbose=1
/usr/lib/ccache/c++   -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security     CMakeFiles/robot_state_publisher.dir/src/joint_state_listener.cpp.o  -o devel/lib/robot_state_publisher/robot_state_publisher -rdynamic devel/lib/librobot_state_publisher_solver.so -llog4cxx /opt/ros/hydro/lib/libroscpp.so -lpthread -lboost_signals-mt -lboost_filesystem-mt -lboost_system-mt /opt/ros/hydro/lib/libcpp_common.so /opt/ros/hydro/lib/libroscpp_serialization.so /opt/ros/hydro/lib/librostime.so -lboost_date_time-mt -lboost_thread-mt /opt/ros/hydro/lib/librosconsole.so -lboost_regex-mt -llog4cxx /opt/ros/hydro/lib/libxmlrpcpp.so /opt/ros/hydro/lib/libtf.so /opt/ros/hydro/lib/libmessage_filters.so /opt/ros/hydro/lib/libtf2_ros.so /opt/ros/hydro/lib/libactionlib.so /opt/ros/hydro/lib/libtf2.so /opt/ros/hydro/lib/libconsole_bridge.so /opt/ros/hydro/lib/libtf_conversions.so /opt/ros/hydro/lib/libkdl_conversions.so /opt/ros/hydro/lib/libkdl_parser.so -ltinyxml /opt/ros/hydro/lib/liburdf.so /opt/ros/hydro/lib/liburdfdom_sensor.so /opt/ros/hydro/lib/liburdfdom_model_state.so /opt/ros/hydro/lib/liburdfdom_model.so /opt/ros/hydro/lib/liburdfdom_world.so /opt/ros/hydro/lib/librosconsole_bridge.so -Wl,-rpath,/tmp/buildd/ros-hydro-robot-state-publisher-1.9.9-0precise-20131207-0746/obj-x86_64-linux-gnu/devel/lib:/opt/ros/hydro/lib: 
/usr/bin/ld: CMakeFiles/robot_state_publisher.dir/src/joint_state_listener.cpp.o: undefined reference to symbol 'KDL::Tree::Tree(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: note: 'KDL::Tree::Tree(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' is defined in DSO /opt/ros/hydro/lib/liborocos-kdl.so.1.2 so try adding it to the linker command line
/opt/ros/hydro/lib/liborocos-kdl.so.1.2: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[4]: *** [devel/lib/robot_state_publisher/robot_state_publisher] Error 1
```

http://jenkins.ros.org/view/HbinP64/job/ros-hydro-robot-state-publisher_binarydeb_precise_amd64/41/console

### PR DESCRIPTION
**Pull request by bit-pirate**
With these changes I'm able again to compile and run the robot_state_publisher again.

I'm a bit confused about the completely missing orocos_kdl dependency though. I wonder how it ever was possible to compile this package at all?! The library and both executables all depend on KDL directly.

So, since it compiled before, I'm not 100% sure my proposed changes are correct/the best way. So far this was the approach I took for all my packages involving KDL. If there is a better solution, please let me know.

### CODE REVIEW

**Comment by tfoote** [comment]
Tested locally, and it's building.  @isucan I'm going to do a quick release to get the buildfarm turning over again. 

This fixes #8 and is the second half of https://github.com/PR2/pr2_controllers/issues/370

**Comment by isucan** [comment]
This looks good actually. Sorry I did not have a chance to look at this sooner.

**Comment by DLu** [comment]
Not sure if this is related: http://answers.ros.org/question/116401/cant-link-to-liborocos-kdlso11/

**Comment by Karsten1987** [comment]
The problem of DLu occurs to me after installing robot-state publisher 1.9.10 as well as orocos-kdl 1.2
any ways to fix that?

**Pull request merged**
