### PR TITLE
[Foxy Backport] fix types in range loops to avoid copy due to different type (#143)

### PR DESCRIPTION
**Pull request by Karsten1987**
backport of #143

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good with green CI.

**Comment by Karsten1987** [comment]
just fyi, I don't have write access to this repo.

**Comment by clalancette** [comment]
> just fyi, I don't have write access to this repo.

Ah, no worries.  Just let me know when CI is done and I'll go ahead and merge.

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12488/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7455/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10201/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12409/)

Linux Clang build: [Build Status](https://ci.ros2.org/job/ci_linux/12489/)

**Comment by clalancette** [comment]
@Karsten1987 I ended up doing a release from the `ros2` branch, and then manually fast-forwarding that onto foxy to keep the branches in sync.  The PR for the new Foxy package is [here](https://github.com/ros/rosdistro/pull/26734).  With that, I'm going to close this out, thanks for the PR.

**Pull request closed without merging**
