### PR TITLE
make rostest in CMakeLists optional (ros/rosdistro#3010)

### PR DESCRIPTION
**Pull request by bulwahn**
This commit has the same intentions as commit f3f1c4d55c on the indigo branch.

### CODE REVIEW

**Comment by sloretz** [comment]
@bulwahn Mind changing package.xml for rostest from `<build_depend>` to `<test_depend>` as well?

**Comment by sloretz** [comment]
@bulwahn FYI I pushed the change to the package.xml onto your branch.

@clalancette mind looking at this once the build passes?

**Comment by bulwahn** [comment]
Thanks, I had this task on my todo list, but was too busy with travelling etc. With that additional commit, it should be ready to merge. Thanks again for taking care and please apologize my slacking in this pull request.

**Review by clalancette — APPROVED** [review]
Looks good to me.  Note that `kdl_parser` and `robot_model/urdf` both have the same issue (rostest is a build_depend, not a test_depend); I'll open some PRs for that.

**Pull request merged**
